#!/bin/bash

export DISPLAY=:0

if [ "$1" == "off" ]
then
    pkill "mplayer"
    xmms2 stop
    pkill "^alarm$"
    amixer sset Master playback 60%
else

    mplayer ~/Music/alarm -loop 1 &
    xmms2 playlist load "wakeup"
    xmms2 play
    
    amixer sset PCM playback 100%
    amixer sset Front playback 100%
    # echo "" | pacmd

    for (( i=5; i <= 100; i=i+5 ))
    do
        amixer sset Master playback $i%
        sleep 5s
    done
fi


