#!/bin/bash

# Fernando Carmona Varo <ferkiwi@gmail.com>
# Time-stamp: <2011-04-15 13:19:13 ferk>

# Simple Alarm
#--------------
# A simple alarm script, it plays a file with mplayer.
#
# It forces you to enter "alarm off" in the terminal for setting the
# alarm off. The typing should make your brain react and wake you
# up... well.. in theory
#
# I use cron to set up the time(s) when the script will be triggered.
# you can also use the "at" command to set temporal alarms.
#--------------

export DISPLAY=:0

if [ "$1" == "off" ]
then
    pkill "mplayer"
    #xmms2 stop
    pkill "^alarm$"
    amixer sset Master playback 60%
else

    SOUND="$HOME/Music/alarm"

    # Make sure pulseaudio is working
    pgrep pulseaudio > /dev/null || start-pulseaudio-x11

    test -f "$SOUND" || sox -n -c1 -t ogg "$SOUND" synth sin %-12 sin %-9 sin %-5 sin %-2 fade h 0.1 1 0.9
    mplayer "$SOUND" -loop 0 -vo null &
    #xmms2 playlist load "wakeup"
    #xmms2 play
    
    amixer sset PCM playback 100%
    amixer sset Front playback 100%
    # echo "" | pacmd

     for (( i=0; i <= 50; i=i+2 ))
    do
        #amixer sset Master playback $i%
	vol.sh +2
        sleep 5s
    done
fi


