#!/bin/sh

# Making sure that webcam works
export LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so

[ $BROWSER ] || BROWSER=$( which chromium || which chromium-browser || which firefox || which dillo )

eval "$BROWSER $@" &
