#!/bin/sh

# Fernando Carmona Varo <ferkiwi@gmail.com

#----
# Script for controlling cmus music player
#
# + If no cmus is running, it will open it on a terminal
# + If run without arguments, it will toggle playback
# + If run with a playlist as argument, it will be loaded
# + If run with other files as argument, they will be added to current playlist
# 
# Other arguments:
#
# --load-pl   Show an Interactive dmenu to load a playlist
#             from the directory set in the CPLAYDIR variable.
#
# --save-pl   Asks for a name and saves the playlist in the
#             playlist directory.
#----

CPLAYDIR=${CPLAYDIR:-"$HOME/.cmus/pls/"}


if ! pgrep "^cmus$" >/dev/null
then
  ${XTERM:-xterm} -e cmus &
  while ! cmus-remote -C; do sleep 1; done
fi

if [ "$1" ]
then
    case "$1" in
	*.pl)
	    cmus-remote -c -P "$1"
	    ;;
	--load-pl)
	    cd $CPLAYDIR
	    cplay "$(find -iname "*.pl" | dmenu || exit)"
	    ;;
	--save-pl)
	    fname=$(echo | dmenu -p 'Name for the playlist (without .pl)')
	    [ "$fname" ] || exit
	    mkdir -p "$PLDIR"
	    cmus-remote -C "save -p -" > "${PLDIR}/${fname}.pl"
	    ;;
	*)
	    cmus-remote -q $@
	    ;;
    esac
else
    cmus-remote -u
fi
