#!/bin/sh

# Modificacion of dmenu_run from suckless, that uses an history file to store the most recent commands introduced and display them the first ones on the list.
#
# Requires dmenu (and stest, which is in the same package)


HISTORY=${XDG_CONFIG_HOME:-"$HOME/.config"}/dmenu_run.history
CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/dmenu_run

cmd=$(
	IFS=:
	if stest -dqr -n "$CACHE" $PATH; then
		stest -flx $PATH | sort -u | tee "$CACHE" | cat "$HISTORY" - | dmenu "$@"
	else
	    cat "$HISTORY" "$CACHE" | dmenu "$@"
	fi
)
${SHELL:-"/bin/sh"} -c "$cmd" &

{ # Update history in background
    [ -z $cmd ] && exit
    (echo "g/${cmd}/d"; echo 'wq') | ex -s "$HISTORY"
    sed -i "1 i $cmd" "$HISTORY"
} &
