#!/bin/sh
#--------
# Convenience script to use with the [[https://github.com/bogner/dtach][dtach tool]].
#
# It will run in a detached session whatever arguments are given,
# assigning automatically a pertinent socket.
#
# If it's called from a symlink starting with "d", it will use
# the name of the symlink as the command to call (for example,
# symlink "dbash" will start a detached bash session).
#
# Also, for non-US keyboard friendliness, it will use Control+Q 
# as default escape shortcut to dettach the session (overriden by 
# DTACH_ESCAPE)
#--------

name=$(basename "$0")

if [ "$name" = "dtach_run" ]
then
	name=$1
else
	bin=${name#d}
fi

if [ -z "$bin $@" ]
then
	cat <<EOF
Usage: ${0##*/} command [ARGUMENTS]

List of currently dettached command sessions:
EOF
	ll "${TMPDIR:-/tmp}/*.dtach_session"
fi

exec dtach -A "${TMPDIR:-/tmp}/$name.dtach_session" \
	 -e ${DTACH_ESCAPE:-^q} \
	 -r ${DTACH_REDRAW:-winch} \
	  $bin "$@"

