#!/bin/sh

#---
# Searches recursivelly the directory for files matching a specific regex
#---

show_usage() {

    cat <<EOF 
  usage: ${0##*/} <pattern> [files or directories]
EOF
    exit
}

custom_ack() {
    [ "$1" ] || show_usage

    REGEX="$1"
    shift

    grep "$@" --color=always --exclude=.svn --exclude=node_modules -nHre "$REGEX" | less -R -F -X
}

if hash ack 2>/dev/null
then
    exec ack "$@"
else
    custom_ack "$@"
fi


