#!/bin/sh

#
# Wrapper for "ln" so that it's straightforward to
# create symbolic links using absolute paths.
# 

# discard args until there's a valid target file
until [ -e "$1" ]
do 
    ARGS="$ARGS $1"
    switch
done

if [ -z $3  ]
then
    ln -s $ARGS "$(readlink -m "$1")" "$2"
else
    echo "This format is not supported for the script: lna TARGET TARGET ... DIRECTORY "
    # TODO: add support
fi


