# -*- org -*-

* Collection of scripts

** Disclaimer

All these scripts are free for anyone to use, redistribute and/or modify
under the terms of the GNU General Public License as published by the FSF,
either version 3 of the License, or (at your option) any later version.

These scripts are distributed in the hope that they will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along
with them.  If not, see <http://www.gnu.org/licenses/>.


** Description of the scripts

*** alarm
A simple alarm script to wake you up, playing a designated xmms2 playlist.

It forces you to enter a command in the terminal for setting the alarm off..
it usually helps me waking up.

*** autoscroll.sh 
Slowly scrolls down with the mouse automatically, so you can read a webpage,
a book, or whatever you want to read on your PC.
Useful when you have your hands busy when eating or doing something.

You can activate/deactivate it by binding a key shortcut to..
:    pkill autoscroll.sh || autoscroll.sh

You need xmacro installed.

*** turboclick.sh
Performs a lot of clicks pretty fast in an endless loop. It can drive you crazy
if you execute it unprepared. I just made it for fun, and beating those silly flash
games about "how fast can you click?"

You can activate/deactivate it by binding a key shortcut to..
:    pkill turboclick.sh || turboclick.sh

You need xmacro installed.

*** browser
This script is set as my default handler for opening webpages.
It's just a wrapper around my browser... I just wanted to keep it synced,
and it allows me to check for multiple browsers, so I can keep the same 
configuration in different systems with different browsers.

*** camrecord
A simple script for recording videos with the webcam

*** dwm.sh
Wrapper script around my dwm window manager instalation

*** e
Not really very useful anymore, since emacs already improved emacsclient invocation,
but this is my wrapper around emacs.

*** ffscreencast.sh
Uses ffmpeg to record a screencast

*** imgupload.py
Uploads a image to imgurl

*** makegrubusb.sh
Script for making bootable usb sticks

*** mount.iso
I don't want to remember what are the arguments for mounting an iso image, so I
made this script to use it instead.

*** powersave.sh
Activates some options for reducing the power consumption.

*** setwallpaper
Sets a random wallpaper from my collection of wallpapers

*** statck
This script checks for temperature and battery and displays a notification
(using notify-send) if the limits are too high.

It can either execute a single time, or be run as a daemon (statck -d) that
will re-run the check each minute.

It has also an option to show the status as a single line (statck -1) which
I use it for displaying it at dwm status line.

*** thumb-extract
Extracts the image thumbnails stored in the "thumb.db" files left out by windows
installations.

*** tree.sh
Shows a list of files/directories and their size (du -akx) and processes it
to a human readable tree shape.

*** vol.sh
Increases/decreases/(un)mutes the volume (uses pulseaudio)

*** xinit.sh
This is the script I'm running for my X.org session

*** Xlaunch
Launches an X.org server in another display with the given program.
If no program is given as argument, choose on dmenu (if available).
*** dmenu_run
Modificacion of dmenu_run from suckless, that uses an history file to store the most recent commands introduced and display them the first ones on the list.

Requires dmenu and lsx to be installed

*** dxmms2
Script to manage xmms2 playlist and collections by means of dmenu.
