#!/bin/bash
##
## setwallpaper
## 
## Made by Fernando Carmona
## Login   <ferk@Mabby>
## 
## Started on  Mon Jul 13 20:37:57 2008 Fernando Carmona
## Last update Mon Jul 14 20:37:57 2008 Fernando Carmona
##


# Wallpapers Directory
walldir=~/Pictures/wallpapers

wallp=$(find "$walldir" -iregex ".*\(jpg\|png\)" | shuf -n 1)

# Darken a bit the image so that it's not very intrusive and blends in the background
convert "$wallp" -brightness-contrast -50x-50 "$HOME/Pictures/wallpapers/.wallpaper"
wallp="$HOME/Pictures/wallpapers/.wallpaper"

# For GNOME wallpaper
gconftool-2 -t string -s /desktop/gnome/background/picture_filename "$wallp"

hash hsetroot && {
    hsetroot -full "$wallp" -gamma 0.6
} || hash feh && {
    feh --bg-max "$wallp"
} || {
    echo "No commandline tool to set the X root background found"
    exit 1
}

