#!/bin/bash

# Fernando Carmona Varo <ferkiwi@gmail.com

#---
# Sets a random wallpaper from my collection of wallpapers
#---

# Wallpapers Directory
walldir=~/Pictures/wallpapers

wallp=$(find "$walldir" -iregex ".*\(jpg\|png\)" | shuf -n 1)

if ! [ -f "$wallp" ]
then
    echo "No wallpaper could be found in $walldir"
    exit 2
fi


# Darken a bit the image so that it's not very intrusive and blends in the background
convert "$wallp" -brightness-contrast -50x-50 "$HOME/Pictures/wallpapers/.wallpaper"
wallp="$HOME/Pictures/wallpapers/.wallpaper"

# For GNOME wallpaper
if hash gconftool-2 2>&-
then
    gconftool-2 -t string -s /desktop/gnome/background/picture_filename "$wallp"
fi


# Detect XDG Session
if [ $XDG_SESSION_ID ]
then
	SESSION_TYPE=$(loginctl show-session $XDG_SESSION_ID -p Type --value)
fi

if [ $SESSION_TYPE = "wayland" ]
then
	# Wayland session
	swaybg -i $HOME/Pictures/wallpapers/.wallpaper &

else
	# X11 session
	if hash hsetroot
	then
		hsetroot -full "$wallp" -gamma 0.6
	elif hash feh
	then
		feh --bg-max "$wallp"
	else
		echo "No commandline tool to set the X root background found"
		exit 1
	fi
fi
