#!/bin/sh

# Fernando Carmona Varo <ferkiwi@gmail.com>
# Time-stamp: <2011-04-15 13:19:13 ferk>

# This script checks for temperature and battery and displays a notification
# (using notify-send) if the limits are too high.
#
# It can either execute a single time, or be run as a daemon (statck -d) that
# will re-run the check each minute.
#
# It has also an option to show the status as a single line (statck -1) which
# can be used for displaying it at applications status line.


NOTIFY='notify-send -u critical -i "dialog-warning.png" '

####
# tempck: Temperature Checking
####
tempck () {
    TEMP=$(sensors | grep -o -e "+.....C[ \n]")
    NTEMP=$(echo "$TEMP" | cut -c "2-3")

    AVGTEMP=0
    for i in $NTEMP
    do
        if [ $i -gt 80 ]
        then
            #notify-send "DANGER!! High temp ($TEMP)" -u critical -i dialog-warning  -h string:synchronouns:"tempsensor"
            $NOTIFY "DANGER!! High temp ($TEMP)"
        fi
		AVGTEMP=$(($AVGTEMP + $i))
		N=$(($N+1))
    done
	AVGTEMP=$((${AVGTEMP}/${N}))
}

####
# battck: Battery Checking
####
battck () {
    BATT=$(acpi -b | cut -d, -f 2 | cut -c 2-)
    NBATT="$(echo "$BATT" | cut -f 1 -d "%")"

    for i in $NBATT
    do
#        if [ "$i" -gt "98" -o "$i" -lt "15" ]
        if [ "$i" -lt "15" ]
        then
	    #notify-send "Battery $BATT!!" -u critical -i "dialog-warning.png" -h string:synchronouns:"battsensor"
	    $NOTIFY "Battery $BATT!!"
        fi
    done
}

####
####
if [ "$#" -eq "0" ]
then
    tempck
    echo -e "- Temp:\n$TEMP"
	battck
	[ -n "$BATT" ] && echo -e "- Batt:\n$BATT"
else
    if [ "$1" = "-d" ]
    then
        while true
        do
            tempck
            battck
            sleep 60
        done &
        echo "Daemon started"
    else
		if [ "$1" = "-1" ]
		then
			tempck
			battck
			#echo "♨${AVGTEMP}ºC♨ ⚡${BATT}⚡"
			echo -n "${AVGTEMP}ºC"
			test -n "$BATT" && echo -n "|${BATT}"
			echo
		else
			echo "usage: checktemp [-d] [-1]"
		fi
	fi
fi

