#!/bin/bash

# Fernando Carmona Varo

##
# Extracts the image thumbnails stored in the "thumb.db" files left out by
# windows installations.
##

function th-extract()
{
    ThumbFile="$1"
    TMPDIR="${ThumbFile/.db/.d}"
    
    echo "Extrayendo $ThumbFile en $TMPDIR..."
    mkdir $TMPDIR 
    vinetto "$ThumbFile"  -o "$TMPDIR" > /dev/null 
}


find ./ -iname Thumbs.db -exec vinetto {} -o {}.d \;



