#!/bin/sh
#
# Umounts every mountpoint in /media mounted
# and asks interactively (in X session) for other umounts
#

{
    echo "----- Active mountpoints -----"
    mount | column -t
    echo "------ Removable mountpoints in /media ------"
    ls /media
    echo "Unmounting every removable storage device found in /media"
    gksudo umount /media/* && echo "Success!" || echo "Operation failed or no mountpoint active."
} |& xmessage -file - -buttons "okay:0,umount other mountpoint:101,remount a removable device:102"

case "$?" in
    101)
	point=$( mount | cut -d" " -f 3 | dmenu -p "mountpoint to unmount: ")
	[ $point  ] && {
            echo "Unmounting $point..."
            gksudo umount $point && echo "Success!" || echo "Operation failed."
	} |& xmessage -file - 
	;;
    102)
	point=$( ls /media | cut -d" " -f 3 | dmenu -p "mountpoint to unmount: ")
	[ $point  ] && {
	    echo "Mounting $point..."
	    gksudo mount $point && echo "Success!" || echo "Operation failed."
        } |& xmessage -file - 
	;;
esac
